### ISSUE TITLE
не стартует проект после клонирования

### ISSUE THREAD

**Issue by petypen** [ViktorErmakov/Kanban_for_1C#9]
Добрый день.

После клонирования проекта в 1С Бухгалтерия не получается запустить приложение. Проблема с объектами:
Неизвестный объект метаданных - Role.kanban_ОсновнаяРоль
Неизвестный объект метаданных - Constant.kanban_КанбанДоскаВключена

**Comment by petypen** [comment]
И еще много замечаний.
* общие модули
* константы

Попробуйте подключить и собрать проект на новой свежей 1С Бухгалтерии

**Comment by ViktorErmakov** [comment]
Доброй ночи. Спасибо за замечания, но я должен сказать, что проект только стартовал)))
Он еще вообще не работает, я просто решил сразу хранить исходники на гитхабе.
Как только будет готово хотя бы частично в одной из конфигураций, я обязательно напишу это в readme, 
а так же выпущу статью на инфостарте.

Хочу заметить сразу что пока проект ориентирован на те конфигурации популярные, где есть справочники Задачи, проект и прочее. 
Такие как "Управление задачами" с гитхаба, СППР и т.д.
Т.е. в расширении будет только доска, без хранимых данных.
